# Generated by Django 4.2.3 on 2023-07-20 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('-created_at',), 'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='content',
            new_name='section',
        ),
    ]
